logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
  config: classpath:log4j2-local.xml

cloud:
  aws:
    region:
      static: ap-southeast-1
    credentials:
      access-key: test
      secret-key: test
    sqs:
      endpoint: "${SQS_URL:http://localhost:4566}"

spring:
  cloud.stream:
    kafka:
      binder:
        brokers: "${KAFKA_BINDER_BROKERS:localhost:9092}"
        replicationFactor: 1
        minPartitionCount: 1
        configuration:
          security.protocol: PLAINTEXT

  redis:
    host: "${REDIS_HOST:localhost}"
    port: 6379
    username: "${REDIS_USERNAME:}"
    password: "${REDIS_PWD:}"
    ssl: "${REDIS_SSL:false}"
    timeout: "${REDIS_TIMEOUT:10s}"
    connectTimeout: "${REDIS_CONNECTION_TIMEOUT:5s}"
    lettuce.pool:
      maxIdle: "${LETTUCE_MAX_IDLE:8}"
      minIdle: "${LETTUCE_MIN_IDLE:4}"
      maxActive: "${LETTUCE_MAX_ACTIVE:16}"
      maxWait: "${LETTUCE_MAX_WAIT:10s}"