server.port: 8801

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: "always"

spring:
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"
  # TODO Spring JPA Config
  jpa:
    database: MYSQL
    openInView: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # https://docs.jboss.org/hibernate/stable/core.old/reference/en/html/configuration-optional.html
        jdbc:
          batch_size: 25
          batch_versioned_data: true
          time_zone: UTC
        order_inserts: true
        order_updates: true
        show_sql: false

  # TODO: Datasource config
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${SEND_MONEY_DB_URL:localhost}:33306/sample?useUnicode=yes&characterEncoding=utf-8&useSSL=${SEND_MONEY_DB_USE_SSL:true}&requireSSL=${SEND_MONEY_DB_REQUIRE_SSL:true}"
    username: "${SEND_MONEY_DB_USER:root}"
    password: "${SEND_MONEY_DB_PWD:root}"
    hikari:
      connectionTimeout: 30000
      maxLifetime: 240000
      maximumPoolSize: 50
      minimumIdle: 5
      idleTimeout: 230000
      data-source-properties:
        prep-stmt-cache-size: 250
        prep-stmt-cache-sql-limit: 2048
        cache-prep-stmts: true
        use-server-prep-stmts: true
  aop:
    auto: false

  redis:
    host: "${REDIS_HOST:localhost}"
    port: 6379
    username: "${REDIS_USERNAME:}"
    password: "${REDIS_PWD:}"
    ssl: "${REDIS_SSL:false}"
    timeout: "${REDIS_TIMEOUT:10s}"
    connectTimeout: "${REDIS_CONNECTION_TIMEOUT:5s}"
    # TODO: Adjust connection pool for Redis using Lettuce. Please update for Jedis according if Jedis is used
    lettuce.pool:
      maxIdle: "${LETTUCE_MAX_IDLE:8}"
      minIdle: "${LETTUCE_MIN_IDLE:4}"
      maxActive: "${LETTUCE_MAX_ACTIVE:16}"
      maxWait: "${LETTUCE_MAX_WAIT:10s}"

feign:
  okhttp:
    enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
